services:

  fastapi:
    container_name: fastapi
    build:
      context: ./requirements/fastapi
      dockerfile: Dockerfile

    volumes:
      - fastapi_src:/app
      - fastapi_log:/log/fastapi
      - fastapi_conf:/tmp/conf

    environment:
      - PATH_LOG
      - PARAMS

    depends_on:
      - postgres

    ports:
      - 8080:80
    networks:
      - fastapi

        #entrypoint: tail -f
        #restart: always

  postgres:
    container_name: postgres
    build:
      context: ./requirements/postgres
      dockerfile: Dockerfile

    volumes:
      - postgres_data:/var/lib/postgresql/data

    environment:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DB
        - POSTGRES_HOST
        - FASTAPI_USER
        - FASTAPI_PASS
        - FASTAPI_DB
    
    expose:
    - 5432
    networks:
      - fastapi

    restart: always

networks:
        fastapi:
                name: fastapi
                driver: bridge

volumes:
  fastapi_src:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./requirements/fastapi/src

  fastapi_conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./requirements/fastapi/conf

  fastapi_log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./log/fastapi

  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/postgres

  postgres_log:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./log/postgres
