#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $FASTAPI_USER WITH PASSWORD '$FASTAPI_PASS';
	CREATE DATABASE $FASTAPI_DB;
	GRANT ALL PRIVILEGES ON DATABASE $FASTAPI_DB TO $FASTAPI_USER;
EOSQL

#/tmp/create_tables.sh
